uploads = []
generated = []

[[outputs]]
id = "RY30P058f9zN9cYbxBp66"
uri = "file://NuclearCraft-ResourcePack.zip"
type = "unspecified"
title = "NuclearCraft Resource Pack"

[[outputs]]
id = "hOE5TX6saNXQg6PRCwLA4"
uri = "file://NuclearCraft_ResourcePack.zip"
type = "unspecified"
title = "NuclearCraft Resource Pack"

[[outputs]]
id = "53aHQL-lguX71_hpTq5gP"
uri = "file://NuclearCraft_Recipes.pdf"
type = "pdf"
title = "NuclearCraft_Recipes.pdf"

[[outputs]]
id = "ITmTqHWFZ_KXdzTwOEKWa"
uri = "file://NuclearCraft Resource Pack 1.0.1.zip"
type = "unspecified"
title = "NuclearCraft Resource Pack 1.0.1"

[[outputs]]
id = "eFoflPKyK1-KO26mta2tX"
uri = "file://NuclearCraft Plutonium Age — Plugin Guide 1.0.1.pdf"
type = "pdf"
title = "NuclearCraft: Plutonium Age — Plugin Guide 1.0.1"

[[outputs]]
id = "1KpJAnZWoS_HmjLhMBiOk"
uri = "file://NuclearCraft-Guide.pdf"
type = "pdf"
title = "NuclearCraft Guide v1.0.0 — 14-page PDF (no blank pages)"

[[outputs]]
id = "c6bkifdbaa4SnbIhz8Vwa"
uri = "file://NuclearCraft-ResourcePack-v1.0.0.zip"
type = "unspecified"
title = "NuclearCraft Resource Pack v1.0.0 — 10 textures included"

[[outputs]]
id = "RlfbzIZJMbR-hK-KkhqwA"
uri = "file://plutonium smp resource pack.zip"
type = "unspecified"
title = "Plutonium SMP Resource Pack (With Textures)"

[[outputs]]
id = "6vA0lGBUrTTKhkzlMalCm"
uri = "file://NuclearCraft-PlutoniumAge-1.0.1.zip"
type = "unspecified"
title = "NuclearCraft: Plutonium Age 1.0.1 (Reload Fix)"

[[outputs]]
id = "0QC6aJGDbkoa0BFSPbt5O"
uri = "file://NuclearCraft-ResourcePack-Final.zip"
type = "unspecified"
title = "NuclearCraft-ResourcePack-Final.zip — fixed pack_format"

[[outputs]]
id = "7cXOFdSjH3ya3Mqyx8oUK"
uri = "file://Last Pack.zip"
type = "unspecified"
title = "Last Pack.zip (42 KB)"

[[outputs]]
id = "YUD9R7FfhSTVNY5ES_2IM"
uri = "file://nuclearcraft-plugin/src/main/resources/NuclearCraft-ResourcePack.zip"
type = "unspecified"
title = "NuclearCraft-ResourcePack.zip"
